[package]
name = "savings-circle-contract"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "20.2.0"

[dev-dependencies]
soroban-sdk = { version = "20.2.0", features = ["testutils"] }